Fix bug in test due to filepath differences.
Strangely this problem only occurred when testing with covr::codecov().
The tests pass on my local Ubuntu and on Travis CI.

$ test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e
"covr::codecov()"
Error: Failure in
`/tmp/RtmphNyS9i/R_LIBS2735270adde9/workflowr/workflowr-tests/testthat.Rout.fail`
> library("testthat")
> library("workflowr")
Loading required package: rmarkdown
This is workflowr version 0.4.0
Please send bug reports and feature requests to:
https://github.com/jdblischak/workflowr/issues
>
> test_check("workflowr")
1. Failure: wflow_open sets correct working directory
(@test-vig-getting-started.R#53)
getwd() not identical to normalizePath(dirname(test_rmd)).
1/1 mismatches
x[1]: "/tmp/RtmpynbKnp/new-27525a81260/analysis"
y[1]: "../../../../../RtmpynbKnp/new-27525a81260/analysis"