Skip failing unit test due to strange filepath only on CRAN Windows servers.
Version: 1.1.0
Check: tests
Result: ERROR
     Running 'testthat.R' [31s]
    Running the tests in 'tests/testthat.R' failed.
    Complete output:
     > library("testthat")
     > library("workflowr")
     This is workflowr version 1.1.0
     Run ?workflowr for help getting started
     >
     > test_check("workflowr")
     -- 1. Failure: wflow_open changes the working directory to the knit directory (@
     `print\(rmd\)` does not match "d:/Rcompile/CRANpkg/local/3.5/workflowr.Rcheck/tests/testthat".
     Actual value: "wflow_open:\\n- New file\(s\):\\n d:/temp/RtmpYLyTaZ/test-wflow_open-12ac030c535d/analysis/do-not-change-wd\.Rmd\\n- Same working directory: d:/RCompile/CRANpkg/local/3\.5/workflowr\.Rcheck/tests/testthat"

     == testthat results ===========================================================
     OK: 601 SKIPPED: 85 FAILED: 1
     1. Failure: wflow_open changes the working directory to the knit directory (@test-wflow_open.R#54)

     Error: testthat unit tests failed
     Execution halted
Flavor: r-release-windows-ix86+x86_64