Do not execute getting-started vignette if pandoc not available.
Not every CRAN machine has pandoc installed. This caused the initial
CRAN submission of workflowr (1.0.1) to generate a WARNING on 2 out of
the 11 builds:

Check Details
Version: 1.0.1
Check: re-building of vignette outputs
Result: WARN
    Error in re-building vignettes:
     ...
    Warning in engine$weave(file, quiet = quiet, encoding = enc) :
     Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling
back to R Markdown v1.
    Quitting from lines 218-220 (wflow-01-getting-started.Rmd)
    Error: processing vignette 'wflow-01-getting-started.Rmd' failed
with diagnostics:
    pandoc version 1.12.3 or higher is required and was not found (see
the help page ?rmarkdown::pandoc_available).
    Execution halted
Flavors: r-patched-solaris-x86, r-release-osx-x86_64