Avoid AppVeyor fs error by converting to absolute path before deleting.
https://ci.appveyor.com/project/jdblischak/workflowr/builds/29558032#L436

Last 13 lines of output:
  [ENOENT] Failed to remove
'../../../../../Users/appveyor/AppData/Local/Temp/1/RtmpuubOh6/working_dir/RtmpSWQ3Tg/test-wflow_publish-5cc286d4971/analysis/cache_cache/html/session-info-chunk-inserted-by-workflowr_dcb4b1f4c87754270381f62dd2d3f529.RData':
no such file or directory
  Backtrace:
   1. testthat::expect_message(...)
   6. workflowr::wflow_publish(...)
   7. workflowr::wflow_build(...)
   8. fs::dir_delete(dir_cache)
   9. fs:::unlink_(files)

  == testthat results
===========================================================
  [ OK: 1688 | SKIPPED: 9 | WARNINGS: 0 | FAILED: 2 ]
  1. Error: wflow_build deletes cache when delete_cache = TRUE
(@test-wflow_build.R#332)
  2. Error: wflow_publish deletes cache when delete_cache = TRUE
(@test-wflow_publish.R#230)

  Error: testthat unit tests failed