Check minimum required versions of dependencies. See #178
Interestingly, this isn't needed for knitr. If there is an outdated
version of knitr, R automatically throws an error upon attaching
or install.packages()

> library(workflowr)
Error: package or namespace load failed for ‘workflowr’ in
loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck =
vI[[j]]):
 namespace ‘knitr’ 1.16 is being loaded, but >= 1.22 is required

I don't know why. In contrast, git2r and rstudioapi can have outdated
versions, and R is silent.